project:
  type: website
  output-dir: docs

website:
  title: "Noah McMahon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Projects

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

